//  const actionTypes = {
//   SIGNUP: "SIGNUP",
//   FETCH_USERS_REQUESTED: "FETCH_USERS_REQUESTED",
//   FETCH_USERS_SUCCESS: "FETCH_USERS_SUCCESS",
//   FETCH_USERS_FAILURE: "FETCH_USERS_FAILURE",
// };
// export default actionTypes;

export const SIGNUP = "SIGNUP";
export const FETCH_USERS_REQUESTED= "FETCH_USERS_REQUESTED";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAILURE = "FETCH_USERS_FAILURE";